<a href="https://colab.research.google.com/github/rushi-k12/Brain_Dead_2k24/blob/prob_1/rushikusuma1_brain_dead_2k24.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestRegressor
from sklearn.metrics import mean_squared_error

In [ ]:
df = pd.read_csv("/content/State_wise_rice_production_in_India.csv" , skiprows=1)
df

,State/Union Territory,2004-05,2005-06,2006-07,2007-08,2008-09,2009-10,2010-11,2011-12,2012-13,2013-14,2014-15,2015-16,2016-17,2017-18,2018-19,2019-20,2020-21,2021-22,2022-23*
0,Andhra Pradesh,9601,11704,11872,13324,14241,10538,7882.4,7746.2,6862.4,6969.7,7233.9,7488.7,7452.4,8166.20,8234.7,8658.9,7882.9,7763.6,8542.3
1,Arunachal Pradesh,135,146.2,146.2,158.1,163.9,215.8,234.0,255.0,263.0,276.2,285.0,204.0,220.0,233.30,240.0,244.7,247.1,252.4,-
2,Assam,3470.7,3552.5,2916,3319,4008.5,4335.9,4736.6,4516.3,5128.5,4927.1,5222.7,5125.1,4727.4,5283.70,5220.6,4984.6,5214.8,4382.1,4979.8
3,Bihar,2472.2,3495.5,4989.3,4418.1,5590.3,3599.3,3102.1,7162.6,7529.3,5505.8,6356.7,6802.2,8239.3,8093.10,6155.5,6298.0,6747.0,7717.0,6725.2
4,Chhattisgarh,4383.3,5011.6,5041.4,5426.6,4391.8,4110.4,6159.0,6028.4,6608.8,6716.4,6322.1,5789.4,8048.4,4930.80,6526.9,6774.8,7161.2,8021.7,8238.3
5,NCT of Delhi,14.3,24,31.1,31.4,31.4,19.3,19.6,19.8,19.7,29.6,25.9,17.3,17.3,16.80,16.8,16.8,19.8,19.0,-
6,Goa,145.2,147.3,130.3,121.6,123.3,100.6,115.0,121.8,122.8,126.5,120.5,115.1,113.2,103.00,98.8,90.4,87.3,90.4,-
7,Gujarat,1238.2,1298,1390,1474,1303,1292,1496.6,1790.0,1541.0,1636.0,1830.9,1702.0,1930.0,1890.90,1912.1,1983.1,2145.7,2101.1,2395.2
8,Haryana,3023,3210,3371,3613,3298,3625,3472.0,3759.0,3976.0,3998.0,4006.0,4145.0,4453.0,4523.38,4516.1,4824.3,4424.9,4618.0,5406.9
9,Himachal Pradesh,122,112.1,123.5,121.5,118.3,105.9,128.9,131.6,125.3,120.8,125.2,129.9,146.6,114.79,114.9,143.8,140.5,167.5,119.2
10,Jammu & Kashmir,492.2,556.8,554,561.3,563.1,497.4,507.7,544.7,818.1,610.9,517.2,646.4,572.2,513.14,615.8,587.0,581.5,492.9,-
11,Jharkhand,1677,1558,2967.8,3336.4,3420.2,1538.4,1110.0,3130.6,3164.9,2810.6,3361.9,2882.2,3841.8,4078.04,2893.9,3012.8,2752.9,2930.5,1399.8
12,Karnataka,3547,5744,3446,3717,3802,3691,4188.0,3955.0,3364.0,3572.6,3541.0,3021.0,2604.8,3017.10,3431.0,3634.5,4291.8,4318.4,4001.3
13,Kerala,667.1,629.9,631,528.5,590.3,598.3,522.7,569.0,508.3,509.2,562.1,549.3,437.1,521.30,578.3,605.6,633.8,487.0,581.4
14,Madhya Pradesh,1169,1656.3,1368.4,1461.9,1559.7,1260.6,1772.1,2227.3,2775.0,2844.8,3625.3,3546.7,4226.8,4123.90,4494.7,4778.2,4413.8,4814.9,7657.2
15,Maharashtra,2164,2695,2569,2996,2284,2183,2696.0,2841.0,3057.0,3120.0,2946.0,2593.0,3109.5,2730.80,3275.7,2897.6,3291.7,3598.1,3899.1
16,Manipur,435.9,386.1,386.1,406.2,397,319.9,521.7,591.0,257.6,398.5,334.1,338.8,430.4,607.80,401.6,385.5,602.2,567.4,-
17,Meghalaya,193.7,151.9,200.2,200,203.9,206.7,207.0,216.5,232.0,273.9,298.2,301.1,203.0,304.60,202.0,303.4,295.9,297.3,-
18,Mizoram,104.1,99.2,29.5,15.7,46,44.3,47.2,54.3,30.5,59.0,60.7,62.1,61.5,59.60,60.0,60.0,62.2,60.9,-
19,Nagaland,259.8,263.1,263.5,290.6,345.1,240.3,381.4,382.4,405.2,429.6,454.2,318.8,336.7,349.60,356.7,363.3,367.4,150.7,-
20,Odisha,6466,6859,6824.7,7540.7,6812.7,6917.5,6827.7,5807.0,7295.5,7613.4,8298.2,5875.4,8325.9,6551.30,7733.7,8360.4,8810.3,9290.8,9621.2
21,Puducherry,65.7,59.9,59.9,53.4,50.8,52.4,52.0,42.1,46.5,49.8,52.7,43.9,52.2,42.50,63.3,59.4,50.0,57.1,-
22,Punjab,10437,10193,10138,10489,11000,11236,10837.0,10542.0,11374.0,11267.0,11107.0,11823.0,11586.2,13381.79,12821.6,11779.3,12783.7,12885.5,13146.7
23,Rajasthan,150.4,153,169.8,259.6,241.1,228.3,265.5,253.4,222.5,312.6,366.7,369.8,452.7,450.87,453.2,480.5,634.0,478.6,577.4
24,Sikkim,21.6,21.5,21.5,22.9,21.7,24.3,21.0,20.9,21.3,20.3,20.1,13.1,19.7,17.63,17.2,16.1,16.2,16.0,-
25,Tamil Nadu,5062.2,5220,6610.6,5040.2,5182.7,5665.2,5792.4,7458.7,4049.9,5349.8,5727.8,7517.1,2369.4,6638.90,6130.9,7171.1,6881.2,7906.6,7850.6
26,Telangana,.,.,.,.,.,.,6535.6,5148.8,4647.6,5755.0,4440.8,3047.0,5173.4,6262.20,6670.0,7427.8,10217.1,12409.6,16013.9
27,Tripura,545.1,552.9,620.5,624.6,627.1,640,702.5,718.3,713.2,711.8,747.0,794.8,814.6,812.10,793.2,810.2,803.1,811.0,-
28,Uttar Pradesh,9555.6,11133.7,11124,11780,13097,10807.1,11992.0,14022.0,14416.0,14636.0,12167.9,12501.0,13754.0,13274.00,15545.3,15517.8,15520.0,15271.5,15171.3
29,Uttarakhand,572,590,556,593,582,608,550.4,594.0,579.8,578.6,603.7,639.1,630.0,646.70,617.6,658.4,714.9,716.1,641.7
30,West Bengal,14884.8,14510.8,14745.9,14719.5,15037.3,14340.7,13045.9,14605.8,15023.7,15370.7,14677.2,15953.9,15302.5,14967.00,16242.2,15881.4,16524.4,16728.7,15636.9
31,ALL INDIA,83131.7,91793.4,93355.3,96692.9,99182.5,89092.9,95979.8,105310.9,105231.6,106645.5,104798.5,104408.2,109698.4,112757.60,116477.8,118870.3,124368.3,129471.4,135542

In [ ]:
# Extract features and target variable
X = df.iloc[:, 1:]  # Features (historical production data)
y = df.iloc[:, -1]  # Target variable (production for the last year)

# Split the data into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# Choose a regression model (Random Forest Regressor as an example)
model = RandomForestRegressor(n_estimators=100, random_state=42)

# Train the model
model.fit(X_train, y_train)

# Evaluate the model
y_pred = model.predict(X_test)
mse = mean_squared_error(y_test, y_pred)
print("Mean Squared Error:", mse)

# Make predictions for future years
future_years = ['2023', '2024', '2025', '2026', '2027']  # Add more years as needed
future_predictions = model.predict(df[future_years])
print("Future Predictions:", future_predictions)

ValueError: could not convert string to float: '2004-05'

In [ ]:
df = df.T

# Convert index to string
df.index = df.index.astype(str)

# Select only rows with valid date values
valid_dates = df.index.str.match(r'\d{4}-\d{2}')  # Match pattern YYYY-YY (e.g., 2004-05)
df = df[valid_dates]

# Convert index to datetime object
df.index = pd.to_datetime(df.index, format='%Y-%y')

# Fill missing values using linear interpolation
df = df.interpolate(method='linear', axis=0)

In [ ]:
# Train-test split
train_data = df.iloc[:-5]  # Data for training (all except last 5 years)
test_data = df.iloc[-5:]   # Data for testing (last 5 years)

# Split features (X) and target (y) for training and testing sets
X_train = train_data.iloc[:, 1:]  # Features (excluding state names)
y_train = train_data.iloc[:, 0]   # Target variable (first column)
X_test = test_data.iloc[:, 1:]    # Features (excluding state names)
y_test = test_data.iloc[:, 0]     # Target variable (first column)

# Choose a regression model (Random Forest Regressor as an example)
model = RandomForestRegressor(n_estimators=100, random_state=42)

# Train the model on the training set
model.fit(X_train, y_train)

# Evaluate the model on the testing set
y_pred = model.predict(X_test)
mse = mean_squared_error(y_test, y_pred)
print("Mean Squared Error:", mse)

# Make predictions for future years
future_years = ['2023', '2024', '2025', '2026', '2027']  # Add more years as needed
future_data = df[future_years]
future_predictions = model.predict(future_data)
print("Future Predictions:", future_predictions)

ValueError: Found array with 0 sample(s) (shape=(0, 32)) while a minimum of 1 is required by RandomForestRegressor.

In [ ]:
print("X_train shape:", X_train.shape)
print("y_train shape:", y_train.shape)
print("X_train:", X_train)
print("y_train:", y_train)

X_train shape: (0, 32)
y_train shape: (0,)
X_train: Empty DataFrame
Columns: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32]
Index: []

[0 rows x 32 columns]
y_train: Series([], Name: 0, dtype: object)

In [ ]:
# Prepare an empty DataFrame to store future predictions
future_predictions_df = pd.DataFrame(index=pd.date_range(start='2023-01-01', periods=5, freq='A'), columns=df.columns)

# Train a model for each state
for state in df.columns:
    # Train-test split
    train_data = df[state].iloc[:-5]  # Data for training (all except last 5 years)
    test_data = df[state].iloc[-5:]   # Data for testing (last 5 years)

    # Split features (X) and target (y) for training and testing sets
    X_train = train_data.drop(columns=['State/Union Territory'])  # Drop 'State' column if it's not needed
    y_train = train_data[state]  # Use the state column as the target variable
    X_test = test_data.drop(columns=['State/Union Territory'])  # Drop 'State' column if it's not needed
    y_test = test_data[state]  # Use the state column as the target variable

    # Choose a regression model (Random Forest Regressor as an example)
    model = RandomForestRegressor(n_estimators=100, random_state=42)

    # Train the model on the training set
    model.fit(X_train, y_train)

    # Make predictions for future years
    future_predictions = model.predict(X_test)
    future_predictions_df[state] = future_predictions

# Print future predictions
print("Future Predictions:")
print(future_predictions_df)

KeyError: 'State/Union Territory'

In [ ]:
train_data

0        Andhra Pradesh
1     Arunachal Pradesh
2                 Assam
3                 Bihar
4          Chhattisgarh
5          NCT of Delhi
6                   Goa
7               Gujarat
8               Haryana
9      Himachal Pradesh
10      Jammu & Kashmir
11            Jharkhand
12            Karnataka
13               Kerala
14       Madhya Pradesh
15          Maharashtra
16              Manipur
17            Meghalaya
18              Mizoram
19             Nagaland
20               Odisha
21           Puducherry
22               Punjab
23            Rajasthan
24               Sikkim
25           Tamil Nadu
26            Telangana
Name: State/Union Territory, dtype: object

In [ ]:
test_data

27          Tripura
28    Uttar Pradesh
29      Uttarakhand
30      West Bengal
31        ALL INDIA
Name: State/Union Territory, dtype: object